<!-- Top Header portion of page - remains unchanged -->
<div id="mastHead">
<h2>The 34th International Workshop on Languages and Compilers for Parallel Computing<br>
  </h2>
<h3>
University of Delaware, Newark, Delaware, USA. 2021<br>
</h3>
</div>
<!-- Left section of page - acts as link Index for pages,
text in this section seldom changes. -->
<div id="linkIndex">
<a href="index.html">Home</a><br>
<a href="cfp.html">Call for Papers</a> <br>
<a href="committee.html">Organizing Committee</a><br>
<a href="submission.html">Submissions</a> <br>
<a href="registration.html">Registration</a><br>
<!-- <a href="hotel.html">Hotel and Transportation</a> --><br>
<a href="program.html">Program</a><br>
<a href="keynote.html">Keynote Speakers</a><br>
<!-- <a href="tutorial.html">Tutorial</a> --><br>
<p class="style1">Sponsored by:</p>
</div>

