<!-- Top Header portion of page - remains unchanged -->
<div id="mastHead">
<h2>The 22nd International Workshop on Languages and Compilers for Parallel Computing<br>
  </h2>
<h3>
Trabant University Center, University of Delaware, Newark, Delaware, USA. October 8-10, 2009<br>
</h3>
</div>
<!-- Left section of page - acts as link Index for pages,
text in this section seldom changes. -->
<div id="linkIndex">
<a href="index.shtml">Home</a><br>
<a href="lcpc-cfp.pdf">Call for Papers</a> <br>
<a href="committee.shtml">Organizing Committee</a><br>
<a href="submission.shtml">Submissions</a> <br>
<a href="registration.shtml">Registration</a><br>
<a href="hotel.shtml">Hotel and Transportation</a><br>
<a href="program.shtml">Program</a><br>
<a href="keynote.shtml">Keynote Speakers</a><br>
<a href="tutorial.shtml">Tutorial</a><br>
<p class="style1">Sponsored by:</p>
<a href="http://www.etinternational.com"><img src="eti-logo.png" width="132" height="121" longdesc="http://www.etinternational.com" style="border-style: none"></a><br>
<a href="http://www.hp.com"><img src="hp-logo.png" width="132" height="121" longdesc="http://www.hp.com" style="border-style: none"></a><br>
<a href="http://www.ibm.com"><img src="ibm-logo.png" width="132" height="121" longdesc="http://www.ibm.com" style="border-style: none"></a><br>
<a href="http://www.nvidia.com"><img src="nvidia-logo.png" width="132" height="121" longdesc="http://www.nvidia.com" style="border-style: none"></a><br>
<a href="http://www.reservoir.com/"><img src="reservoir-logo.png" width="132" height="72" longdesc="http://www.reservoir.com/" style="border-style: none"></a><br>
</div>

